#!/usr/bin/bash

set -e

. ~/.nvm/nvm.sh

cd ~/LeoFalco/genyo

nvm install
nvm use

git pull
npm install

date=$(date '+%Y-%m-%d_%H_%M_%S')

logs_dir=/home/leofalco/LeoFalco/common-sh-scripts/logs

# if log dir doesn't exist, create it
if [ ! -d "$logs_dir" ]
then
  mkdir -p $logs_dir
fi

npm run invoke | tee $logs_dir/$date.log