#!/usr/bin/bash

set -e

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$1" = "--no-verify" ]; then
  echo "git push -u origin $current_branch -f --no-verify"
  git push -u origin $current_branch -f --no-verify
else
  echo "git push -u origin $current_branch -f"
  git push -u origin $current_branch -f
fi
